New punch screen
Codeminer42/punch_clock_mobile pull request #12
Opened 2022-05-12 19:42 UTC by JRRGomes

Created the New Punch screen

2022-05-12 20:14 UTC, negreirosleo commented on src/screens/new-punch/compose/Select.js
> +  color: '#808080',
Nao tem essa cor no tema?

2022-05-12 20:14 UTC, negreirosleo commented on src/screens/new-punch/compose/Select.js
> +            onValueChange={(value) => console.log(value)}
esse console.log era pra estar aqui?

2022-05-12 21:15 UTC, JRRGomes commented
### New punch screen

![IMG_4754](https://user-images.githubusercontent.com/19179208/168169225-efc41309-ed7b-4b96-a2f3-209a3ac50b35.jpeg)

2022-05-13 12:27 UTC, JRRGomes commented on src/screens/new-punch/compose/Select.js
> +  color: '#808080',
Eu to com essa dúvida na verdade pq não consegui colocar o valor do tema, por ser um objeto e não um styled component. 
E também a cor escolhida não aparece na tela, somente quando o select é pressionado e aparecem as opções é que a cor escolhida aparece, com na imagem abaixo (coloquei uma cor laranja de exemplo):

![image](https://user-images.githubusercontent.com/19179208/168282839-4f6b2db3-59d2-4f89-bb5c-b00db41876a9.png)

2022-05-13 12:28 UTC, JRRGomes commented on src/screens/new-punch/compose/Select.js
> +            onValueChange={(value) => console.log(value)}
ops

2022-05-24 00:38 UTC, belgamo requested changes
Vamos adicionar um componente genérico pro botão, pro select e pro texto. Assim facilitaremos o reuso.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/compose/Select.js
> +  color: '#808080',
Você poderia simplesmente importar o objeto de tema.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/compose/Select.js
> +export const Select = () => {
Seria interessante colocar isso na pasta `components`, pois isso pode ser reusado em outras telas do app.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +            <Date>27, Segunda-feira</Date>
Aqui você pode instanciar uma nova data e formatar com o `date-fns`.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +              <TimeInput placeholder='08:00' keyboardType='numeric' placeholderTextColor='grey' />
Esse placeholder funciona como valor padrão pro `TimeInput`? Se não, seria interessante.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +            onPress={() => true}
Já dá pra chamar uma funcão pra lidar com o envio de form, deixando um objeto json pronto pra no futuro mandar pra API.

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +  return (
Acho que faltou gerenciar o estado do form... Sugiro [react-hook-form](https://react-hook-form.com/get-started#ReactNative)

2022-05-24 00:38 UTC, belgamo commented on src/styles/theme.js
> +  cancelButton: "#C4C4C4",
Eu não acho que vale a pena adicionar isso no tema. Melhor consumir algum tom de cinza já existente ou usar uma lib de que te dê tons mais claros ou escuros de uma cor https://polished.js.org/docs/

2022-05-24 00:38 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.style.js
> +  width: 100%;
Precisa da largura 100%? Você já setou `flex: 1`

2022-05-24 00:38 UTC, belgamo commented on src/styles/theme.js
> +  input: moderateScale(30),
Com excessão do `xxl`, todos os outros eu também acho que não vale a pena.

2022-06-27 12:18 UTC, belgamo requested changes
1. Renomeie os arquivos de `.style`para `.styles`

PR tá ficando TOP, uma polida final e vamos mergear. Parabéns!

2022-06-27 12:18 UTC, belgamo commented on src/components/button/Button.js
> +`;
Move isso pra um arquivo style por favor.

2022-06-27 12:18 UTC, belgamo commented on src/components/button/Button.js
> +export const Button = ({ color, size, onPress, title }) => (
Usa o export default pra esse botão.

2022-06-27 12:18 UTC, belgamo commented on src/components/select/Select.js
> +      }}
Faltou um tab aqui :nail_care:

2022-06-27 12:18 UTC, belgamo commented on src/components/select/Select.js
> +  const pickerSelectStyles = StyleSheet.create({
Move esses estilos pro topo do arquivo e use os helpers de scanle.

2022-06-27 12:18 UTC, belgamo commented on src/screens/calendar/calendar-screen.js
> +    </Container>
Faltou um tab aqui :nail_care:

2022-06-27 12:18 UTC, belgamo commented on src/styles/theme.js
> +  input: moderateScale(30),
Não vale a pena colocar um tamanho para input aqui.

2022-06-27 12:18 UTC, belgamo commented on src/components/select/Select.js
> +  `;
Mover pra um arquivo de styles.

2022-06-27 12:18 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                <ControlledInput
Aqui tem um tab a mais... :nail_care:

2022-06-27 12:18 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                )}
Formatação estranha... :nail_care:

2022-06-27 12:18 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                )}
Formatação estranha... :nail_care:

2022-07-08 17:40 UTC, belgamo requested changes
Renomar os arquivos no padrão `foo-bar.js`

2022-07-08 17:40 UTC, belgamo commented on src/components/button/Button.js
> +}
Mover pro topo do arquivo.

2022-07-08 17:40 UTC, belgamo commented on src/components/button/Button.styles.js
> +
Remover espaço em branco :nail_care:

2022-07-08 17:40 UTC, belgamo commented on src/components/input/Input.js
> +};
Não precisamos disso, vamos ter um height default e aceitar um height customizado.

2022-07-08 17:40 UTC, belgamo commented on src/components/select/Select.js
> +});
Mover pro topo do arquivo.

2022-07-08 17:40 UTC, belgamo commented on src/components/select/Select.styles.js
> +};
Mesma coisa do caso do input.

2022-07-08 17:40 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +      afternoonTo: "18:00",
Vamos usar essa lib pra selecionar horas. https://github.com/henninghall/react-native-date-picker

2022-07-08 17:40 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                  <ErrorMessage>Insira uma hora.</ErrorMessage>
"Selecione as horas"

2022-07-08 17:40 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                  <ErrorMessage>Insira uma hora.</ErrorMessage>
"Selecione as horas"

2022-07-08 17:40 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.js
> +                  <ErrorMessage>Insira uma hora.</ErrorMessage>
"Selecione as horas"

2022-07-08 17:40 UTC, belgamo commented on src/screens/new-punch/new-punch-screen.styles.js
> +  position: absolute;
Vamos mostrar os erros somente após o usuário clicar em salvar usando `react-native-toast-message`

2022-07-26 13:25 UTC, merged